### ISSUE TITLE
version 0.10.1 causes "GIT_DISCOVERY_ACROSS_FILESYSTEM" warnings on Heroku

### ISSUE THREAD

**Issue by xavriley** [skylightio/skylight-ruby#58] opened 2016-01-11 09:58 UTC
Hi,

I've seen a couple of cases now where using the latest `0.10.1` version of this gem causes the following warnings to be displayed when deploying to Heroku (as part of the build output):

```
remote: fatal: Not a git repository (or any parent up to mount point /tmp)
remote: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I don't have much more information on where this is coming from at the moment. In the past on Heroku this error has been seen where a dependency starts shelling out to git somewhere. I just thought I'd make a note here for now. If I have anything more concrete I'll post back here.

**Comment by DannyBen** [comment] 2016-01-11 10:13
Had the same issue. Maybe the problem is [in this line](https://github.com/skylightio/skylight-ruby/blob/d6e3fd1f3a5ae357b2de60629a238556739a3556/lib/skylight/util/deploy.rb#L61)?

**Comment by wagenet** [comment] 2016-01-14 00:32
It is indeed that line and can be safely ignored. This error will be fixed in the next release. Sorry for the trouble.

**Comment by rhuppert** [comment] 2016-01-18 16:13
I wasted my weekend tracking this error, although my build apparently succeeded.  
I had actually tried reverting skyligh to 0.10.0, but  mistakenly left the "~>" instead of using the"=" mark, so I suppose I was hoisted by my own petard.
Thanks @xavriley for dehoisting me.

**Comment by wagenet** [comment] 2016-01-19 17:16
@rhuppert my sincere apologies for the wasted time here.

I've gone ahead and release 0.10.2 with a quick fix for this. There's also a 1.0.0 beta out now for those interested.

**Closed by wagenet** 2016-01-19 17:16 UTC

**Comment by rhuppert** [comment] 2016-01-19 17:35
@wagenet thanks for that. Like I said, I could have avoided it if I had paid better attention. My lost weekend pales in comparison to the insight and performance increases I have realized after implementing Skylight.  Kudos to you and the Skylight team.

**Comment by wagenet** [comment] 2016-01-19 18:17
@rhuppert glad you're taking it in stride. I still hate to have even a small part in anyone's wasted weekend!
