### ISSUE TITLE
Panik and stuck Sidekiq process (RuntimeError/E9999)

### ISSUE THREAD

**Issue by tisba** [skylightio/skylight-ruby#176] opened 2021-02-20 11:03 UTC
We had an issue in production, where a sidekiq worker got stuck for ever. We were not able to reproduce the issue and it only has occurred once so far, but found the following error in the sidekiq log hinting at a crash related to skylight:

```
Feb 09 21:18:21 sidekiq[2622246]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
Feb 09 21:18:21 sidekiq[2622246]: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Feb 09 21:18:21 sidekiq[2622246]: [2021-02-09T21:18:21.705145561+01:00] ERROR -- Skylight [skylight::c_api::safe_extern]: [SKYLIGHT] internal error: SkError { kind: RuntimeError("internal error", Some("called `Option::unwrap()` on a `None` value")), silenced: false }
Feb 09 21:18:21 sidekiq[2622246]: /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/instrumenter.rb:172:in `native_stop': [E9999] Skylight::NativeError [Instrumenter#native_stop] (Skylight::NativeError)
```

One "special" thing that we are doing in the sidekiq job is using the parallel gem to fork. That might be related to the issue.

We are using:

* Ruby 2.7.2
* Rails 6.1.2.1
* Skylight 4.3.2

<details>
  <summary>Trace from sidekiq log</summary>

```
Feb 09 21:18:21 sidekiq[2622246]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
Feb 09 21:18:21 sidekiq[2622246]: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Feb 09 21:18:21 sidekiq[2622246]: [2021-02-09T21:18:21.705145561+01:00] ERROR -- Skylight [skylight::c_api::safe_extern]: [SKYLIGHT] internal error: SkError { kind: RuntimeError("internal error", Some("called `Option::unwrap()` on a `None` value")), silenced: false }
Feb 09 21:18:21 sidekiq[2622246]: /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/instrumenter.rb:172:in `native_stop': [E9999] Skylight::NativeError [Instrumenter#native_stop] (Skylight::NativeError)
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/instrumenter.rb:172:in `shutdown'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/instrumentable.rb:83:in `block in stop!'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/instrumentable.rb:77:in `synchronize'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/instrumentable.rb:77:in `stop!'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/instrumentable.rb:11:in `block (2 levels) in included'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:8:in `fork'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:8:in `fork'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `worker'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:441:in `block in create_workers'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each_with_index'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `create_workers'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:380:in `work_in_processes'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:283:in `map'
Feb 09 21:18:21 sidekiq[2622246]:         from /srv/www/forge/releases/20210208164134/app/models/metrics/raw_data.rb:50:in `block in process_all'
[...]
```

</details>

**Comment by zvkemp** [comment] 2021-02-22 17:27
Hi @tisba, thanks for the report. Can you be more specific about how you are using the `parallel` gem (i.e., at what point in the job lifecycle is it called, and whether you are using processes or threads)?

**Comment by tisba** [comment] 2021-02-22 17:42
We are using the `parallel` gem to fork multiple processes (to gain "true" parallelism as we run on CRuby).

In this case, a sidekiq job is scheduled, we're doing a bunch of things to setup and prepare things (some ActiveRecord things mostly) and then fork off processes to and pass a portion of the work to be done to each process. The work results of each process is then merged together afterwards. Think "map & reduce" style processing. Forking processes helps with speeding up things significantly, because most of the work is quite CPU intensive and at the same time can be broken down into smaller chunks very easily.

Hope that helps, if not, please keep asking.

**Comment by zvkemp** [comment] 2021-02-22 18:00
So does your job look something like this?

```ruby

class MyWorker
  include Sidekiq::Worker

  def perform(*args)
    Parallel.map(collection, in_processes: nproc) do |item|
       ...
    end
  end
end
```

(it's ok if it's not exactly like this, just trying to determine whether the fork happens inside `#perform`)

**Comment by zvkemp** [comment] 2021-02-23 23:23
@tisba 
I've been able to reproduce an issue with process forks (though it's not _exactly_ the same error you described, it is basically what I would expect to happen). There is quite a lot of behavior in the exit handlers for Sidekiq and Skylight, some of which you may not want to run when the forked processes exit. I'd have to sit down and map out all of the potential interactions, but for now I would expect neither Skylight nor Sidekiq to behave exactly as designed here.

We can try adding fork detection to Skylight to ensure the instrumenter doesn't hang on shutdown (which is the part I can't reproduce; in my version the exit handler simply panics and exits non-zero), but at this point I can't say for sure when that would land in a release.

**Comment by tisba** [comment] 2021-03-12 09:15
Sorry I totally forgot coming back to this :( Your example looks correct from the structure.

Also, we updated to skylight 5 and are seeing now A LOT more of this issue (at least they look very similar). Although we did not have a process hanging, we saw hundreds of these issues :(

Here is an example:

```
Mar 11 13:16:01 sidekiq[468551]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/thread/mod.rs:1245:48
Mar 11 13:16:01 sidekiq[468551]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar 11 13:16:01 sidekiq[468551]: /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight/instrumenter.rb:192:in `native_stop': [E9999] Encountered an unknown internal error [Instrumenter#native_stop] (Skylight::NativeError)
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight/instrumenter.rb:192:in `shutdown'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight.rb:128:in `block in stop!'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight.rb:121:in `synchronize'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight.rb:121:in `stop!'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight.rb:63:in `block in <module:Skylight>'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/fork_tracker.rb:8:in `fork'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/fork_tracker.rb:8:in `fork'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `worker'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:441:in `block in create_workers'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each_with_index'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `create_workers'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:380:in `work_in_processes'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/shared/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:283:in `map'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/releases/20210311112506/app/models/metrics/raw_data.rb:50:in `block in process_all'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/releases/20210311112506/app/models/perf_tools.rb:58:in `timing'
Mar 11 13:16:01 sidekiq[468551]:         from /srv/www/forge/releases/20210311112506/app/models/metrics/raw_data.rb:44:in `process_all'
[…]
```

Is there a way to disable skylight for parts of the code, so we avoid the forking issue? Or do we have to disable skylight for sidekiq altogether for now?

**Comment by zvkemp** [comment] 2021-03-12 16:59
You can try calling `Skylight.mute` with a block, i.e. `Skylight.mute { Parallel.map { ... } }`, however, this only disables data collection, and probably wouldn't have any effect on the errors you're seeing. Skylight uses a mutex in order to share its instrumenter among all Ruby threads, but since you're forking from a Sidekiq worker thread, we have no way of guaranteeing that another thread isn't holding the mutex at the time of the fork, so the behavior at that point forward is at best undefined (similar caveats apply for everything happening in Ruby-land). This is why it's generally advised not to fork multi-threaded processes, and always to accompany `fork` with an immediate `exec`.

My current recommendation is either not to use Skylight in Sidekiq, or refactor your worker into multiple workers that can perform as a batch without using `parallel`.

**Comment by tisba** [comment] 2021-07-15 18:47
Hey @zvkemp. I was wondering if there is any update on this issue? We've kept skylight disabled for our sidekiq jobs, but that's kind of a bummer… 😢

**Comment by zvkemp** [comment] 2021-09-07 18:23
Hi @tisba, apologies that I missed your latest message until now. I've discussed the issue with a colleague, and we feel that restructuring Skylight to bypass this issue would add unnecessary complexity and provide comparatively little value (given that this is essentially off-label usage). I agree that it's a bummer, but for right now this will remain a WONTFIX.

I know Sidekiq Pro has a batching feature that gives you the same benefits within your existing worker processes (i.e., no additional forking), and there may be other third-party gems that offer similar functionality.

**Closed by zvkemp** 2021-09-07 18:23 UTC

**Comment by tisba** [comment] 2021-09-13 12:31
No worries and thanks for the heads up, @zvkemp!

Maybe you should clear messaging in the docs, that skylight "does not support forking".
