### ISSUE TITLE
Wrong exit code in rspec.

### ISSUE THREAD

**Issue by changs** [skylightio/skylight-ruby#29] opened 2015-04-10 12:37 UTC
Hi. I've been getting wrong exit code when running rspec in a Rails project. This happens only when Skylight gem is included. 
It happens both on my computer (OSX) and on CircleCI. 

Env:
```
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
Rails 4.0.13
rspec 3.0.0
```

It works though when I change this line https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/instrumenter.rb#L61 to enable it also for ruby 2.1.5.

**Comment by halorgium** [comment] 2015-04-10 17:01
@changs interesting! we had only thought the issue was present in 1.9.2. 
We'll see about getting this issue fixed. Getting `at_exit` hooks right is a tricky thing!

**Comment by jamesotron** [comment] 2015-04-21 01:36
I'm having the same problem with Ruby 2.1.5 and 2.1.6. Our CI server has been happily deploying failing builds for some time! :sob:

**Comment by jamesotron** [comment] 2015-04-21 01:41
@changs work around is to move `skylight` into a `production` group in your `Gemfile`.

**Comment by wagenet** [comment] 2015-04-22 03:30
See also https://bugs.ruby-lang.org/issues/8501 and https://bugs.ruby-lang.org/issues/8501. Looks like a regression in Ruby, but we can likely work around it.

**Comment by wagenet** [comment] 2015-07-25 00:34
I've verified that this issue doesn't exist in 2.2.0, of course not everyone may be able to upgrade.

**Comment by wagenet** [comment] 2015-07-25 00:55
@jamesotron, @changs: Sorry for taking forever to address this. I did some investigation and it turns out the example failure cases at both https://bugs.ruby-lang.org/issues/5218 and https://bugs.ruby-lang.org/issues/8501 seem to do the right thing on 2.1.5p273. Is there any chance you could put together a simple script that does fail? I'd be happy to get this fixed but I'm having trouble figuring out the exact failure scenario.

**Comment by wagenet** [comment] 2015-10-15 22:49
Closing until more information is provided.

**Closed by wagenet** 2015-10-15 22:49 UTC
Labels: bug
