### ISSUE TITLE
Don't assume `ENV['HOME']` is defined

### ISSUE THREAD

**Issue by sandstrom** [skylightio/skylight-ruby#61] opened 2016-04-04 13:24 UTC
When `HOME` isn't set, the following line throws an exception:

> **couldn't find HOME environment -- expanding '~'**
> 
> /home/vagrant/.gem/ruby/2.1.2/gems/skylight-0.10.3/lib/skylight/user_config.rb:17:in 'expand_path'
> /home/vagrant/.gem/ruby/2.1.2/gems/skylight-0.10.3/lib/skylight/user_config.rb:17:in 'file_path'
> /home/vagrant/.gem/ruby/2.1.2/gems/skylight-0.10.3/lib/skylight/user_config.rb:25:in 'reload'
> /home/vagrant/.gem/ruby/2.1.2/gems/skylight-0.10.3/lib/skylight/user_config.rb:13:in 'initialize'
> /home/vagrant/.gem/ruby/2.1.2/gems/skylight-0.10.3/lib/skylight/user_config.rb:9:in 'new'
> /home/vagrant/.gem/ruby/2.1.2/gems/skylight-0.10.3/lib/skylight/user_config.rb:9:in 'instance'
> /home/vagrant/.gem/ruby/2.1.2/gems/skylight-0.10.3/lib/skylight/railtie.rb:42:in 'block in <class:Railtie>'
> /home/vagrant/.gem/ruby/2.1.2/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in 'instance_exec'
> /home/vagrant/.gem/ruby/2.1.2/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in 'run'
> /home/vagrant/.gem/ruby/2.1.2/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in 'block in run_initializers'

It's pretty common to have no home-directory (also, some dists set it to `/nonexistent` in various cases, but that wouldn't throw an exception).

**Comment by bf4** [comment] 2016-09-18 20:16
Duplicate of https://github.com/skylightio/skylight-ruby/issues/71 I think?

Here's what we do in [SimpleCov](https://github.com/colszowka/simplecov/blob/257e26394c464c4ab388631b4eff1aa98c37d3f1/lib/simplecov/defaults.rb#L97-L103)

```ruby
require "etc"
home_dir = File.expand_path("~") || Etc.getpwuid.dir || (ENV["USER"] && File.expand_path("~#{ENV['USER']}"))
if home_dir
  # do something with home_dir
end
```

**Comment by sandstrom** [comment] 2016-09-18 20:41
friendly ping @wagenet

**Comment by wagenet** [comment] 2016-09-27 16:04
@bf4 @sandstrom is it common for `HOME` to not be set? If so, is @bf4's solution something we should incorporate. Would it be considered correct for general use?

**Comment by sandstrom** [comment] 2016-09-27 16:27
@wagenet Yes, pretty common (in startup scripts, scheduled scripts, etc). 

`File.expand_path('~')` is basically the same as `ENV['home']`. But `Etc.getpwuid.dir` is using a difference mechanism, and would be a good fallback.

Here is a similar handling in Passenger:
https://github.com/phusion/passenger/blob/d30ace17c4026d48138b22acca8696a2a08b43f9/src/ruby_supportlib/phusion_passenger.rb#L317

**Comment by wagenet** [comment] 2016-09-27 16:35
@sandstrom we're not actually looking at `HOME` it looks like it's Ruby doing it when you `expand_path('~')`. Looks like Thor, which we use for the CLI (though not this error isn't from our CLI), has the following method:

```ruby
      def user_home
        @@user_home ||= if ENV["HOME"]
          ENV["HOME"]
        elsif ENV["USERPROFILE"]
          ENV["USERPROFILE"]
        elsif ENV["HOMEDRIVE"] && ENV["HOMEPATH"]
          File.join(ENV["HOMEDRIVE"], ENV["HOMEPATH"])
        elsif ENV["APPDATA"]
          ENV["APPDATA"]
        else
          begin
            File.expand_path("~")
          rescue
            if File::ALT_SEPARATOR
              "C:/"
            else
              "/"
            end
          end
        end
      end
```

**Comment by sandstrom** [comment] 2016-09-27 17:06
Yes, I noticed that code too (Thor).

I think `Etc.getpwuid.dir` would be a good fallback.

**Comment by bf4** [comment] 2016-09-28 14:35
@wagenet you want a PR or continue discussion?

**Comment by wagenet** [comment] 2016-09-28 15:55
@bf4 PR would be great! Otherwise I will try to get to it soon. You'll need to [sign the CLA](https://docs.google.com/spreadsheet/viewform?usp=drive_web&formkey=dHJVY1M5bzNzY0pwN2dRZjMxV0dXSkE6MA#gid=0) if you haven't yet.

**Comment by bf4** [comment] 2016-10-09 23:03
@wagenet And apparently I've made a similar comment before in https://github.com/lsegal/yard/pull/860#issuecomment-120762660  (which resulted in [this patch](https://github.com/lsegal/yard/commit/d2b04f1ff4ab932f15b163e5185f38cfcb88383a)). I just submitted the CLA. I don't seem to have signed it before.

**Closed** 2016-10-13 21:48 UTC
